apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-getting-started
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: node-pod
  template:
    metadata:
      labels:
        app: node-pod
    spec:
      containers:
      - name: express-getting-started
        image: abhijithababhijith/getting-started-expressjs
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  type: NodePort
  selector:
    app: node-pod
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30004


