apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-example
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      name: 'pods'
      labels:
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx