apiVersion: apps/v1
kind: Deployment
metadata:
   name: result-frontend
   labels:
      app: result-frontend
      tier: result-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-pod
  template:
    metadata:
      name: result-pod
      labels:
        app: result-pod
    spec:
      containers:
        - name: result
          image: dockersamples/examplevotingapp_result:before
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result-service
spec:
  type: NodePort
  selector:
    app: result-pod
  ports:
    - port: 5001
      targetPort: 80
      nodePort: 31001