apiVersion: apps/v1
metadata:
  name: vote-frontend
  labels:
    app: vote-frontend
kind: Deployment
spec:
  replicas: 2
  selector:
    matchLabels:
        app: vote-pod
        tier: vote-pod
  template:
    metadata:
      name: vote-pod
      labels:
        app: vote-pod
        tier: vote-pod
    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  type: NodePort
  selector:
    app: vote-pod
  ports:
  - port: 5000
    targetPort: 80
    nodePort: 31000
